# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # 使用別人寫好的安裝 Action
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '>=14.17.1'

      # 安裝 npm 套件
      - name: Install packages
        run: npm install
        
      # 建置專案資料夾
      - name: Build page
        run: npm run build
        
      # 部署到 GitHub-pages，使用 package.json 的設定
      - name: Deploy pages
        run: npm run deploy
